version: "3.7"

services:
  typebot-db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot_builder:
    ports:
      - 4000:3000
    image: baptistearno/typebot-builder:2.20.0
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - ENCRYPTION_SECRET=7/l2NKGhkMUHRV0dt/g8hD2YNopCrAeH
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - DISABLE_SIGNUP=false
      - ADMIN_EMAIL=contato@fluxosmm.com
      - NEXT_PUBLIC_SMTP_FROM=='Suporte' <contato@fluxosmm.com>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=contato@fluxosmm.com
      - SMTP_PASSWORD=Intruso99@
      - SMTP_HOST=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      # Configurações do Typebot e Google Cloud
      - GOOGLE_CLIENT_ID=http://1057579664250-0qmbhq4tgkfk3u0cteggffamrsuek2ek.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      # Configurações do Typebot e Minio
      - S3_ACCESS_KEY=OqCEOydCqDaVJ2eXw8TQ
      - S3_SECRET_KEY=ViK4TTnGK05LbY2kmbXLmwuW3uYeqtwvMEC9inFh
      - S3_BUCKET=typebot
      - S3_ENDPOINT=db.fluxosmm.com


  typebot_viewer:
    ports:
      - 4001:3000
    image: baptistearno/typebot-viewer:2.20.0
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - ENCRYPTION_SECRET=7/l2NKGhkMUHRV0dt/g8hD2YNopCrAeH
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      # Configurações do Typebot e Google Cloud
      - GOOGLE_CLIENT_ID=http://1057579664250-0qmbhq4tgkfk3u0cteggffamrsuek2ek.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      # Configurações do Typebot e Minio
      - S3_ACCESS_KEY=OqCEOydCqDaVJ2eXw8TQ
      - S3_SECRET_KEY=ViK4TTnGK05LbY2kmbXLmwuW3uYeqtwvMEC9inFh
      - S3_BUCKET=typebot
      - S3_ENDPOINT=db.fluxosmm.com


  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Mfcd62KKxTr!!Mfcd62!!
      - MINIO_BROWSER_REDIRECT_URL=https://s3.fluxosmm.com
      - MINIO_SERVER_URL=https://db.fluxosmm.com
  
volumes:
  minio_data:
  db_data:

